basePath: /api
info:
  contact:
    name: Github Issues
    url: https://github.com/jinyaoMa/vue-gin-systray-starter/issues
  description: '"app"'
  license:
    name: MIT
    url: https://github.com/jinyaoMa/vue-gin-systray-starter/blob/main/LICENSE
  title: app
  version: 0.0.0
paths: {}
securityDefinitions:
  BearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
