basePath: /api
definitions:
  formats.JSONError:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  formats.JSONResult:
    properties:
      data: {}
      success:
        type: boolean
    type: object
  formats.UserDataResult:
    properties:
      account:
        type: string
      active:
        type: boolean
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      permission:
        type: string
    type: object
info:
  contact:
    name: Github Issues
    url: https://github.com/jinyaoMa/vue-gin-systray-starter/issues
  description: '"app"'
  license:
    name: MIT
    url: https://github.com/jinyaoMa/vue-gin-systray-starter/blob/main/LICENSE
  title: app
  version: 0.0.0
paths:
  /users/all:
    get:
      consumes:
      - application/json
      description: Get all users
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/formats.JSONResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/formats.UserDataResult'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/formats.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/formats.JSONError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/formats.JSONError'
      security:
      - BearerToken: []
      summary: All
      tags:
      - Users
securityDefinitions:
  BearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
